### PR TITLE
Add WarpFlow support to OpenCV 3.1.0

### PR DESCRIPTION
**Pull request by victorhcm**
Almost done! I'm only having an issue with the Python interface, which I'm trying to figure it out. @yjxiong don't merge it yet, please :)

**EDIT:** Done. Forgot to instantiate `alg_tvl1` in the constructor, _tisk tisk_

### CODE REVIEW

**Comment by yjxiong** [comment]
Well done! Please let me know when it is good to go.
And the python script is very handy :)

**Comment by victorhcm** [comment]
Tested dense flow and warp flow and everything seems to be fine. It is good to go :)

**Comment by yjxiong** [comment]
Thanks! I will update the README to help 3.1 users to find the code.

**Comment by zhangyuygss** [comment]
Got this error while building with opencv3.1, any suggestions on solving this problem?
`
-- The C compiler identification is GNU 4.9.4
-- The CXX compiler identification is GNU 4.9.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test COMPILER_SUPPORTS_CXX11
-- Performing Test COMPILER_SUPPORTS_CXX11 - Success
-- Performing Test COMPILER_SUPPORTS_CXX0X
-- Performing Test COMPILER_SUPPORTS_CXX0X - Success
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.26") 
-- Found LIBZIP: /usr/lib/libzip.so  
-- Boost version: 1.61.0
-- Found the following Boost libraries:
--   python
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.4m.so (found version "3.4.3") 
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CUDA_USE_STATIC_CUDA_RUNTIME


-- Build files have been written to: /disk4/zhangyu/codes/paperCodes/dense_flow/build
(py35) zhangyu@GPUServer2:/disk4/zhangyu/codes/paperCodes/dense_flow/build$ make -j
Scanning dependencies of target denseflow
[ 11%] [ 22%] [ 33%] [ 44%] [ 55%] Building CXX object CMakeFiles/denseflow.dir/src/common.cpp.o
Building CXX object CMakeFiles/denseflow.dir/src/dense_flow.cpp.o
Building CXX object CMakeFiles/denseflow.dir/src/dense_warp_flow_gpu.cpp.o
Building CXX object CMakeFiles/denseflow.dir/src/dense_flow_gpu.cpp.o
Building CXX object CMakeFiles/denseflow.dir/src/zip_utils.cpp.o
Linking CXX static library libdenseflow.a
[ 55%] Built target denseflow
Scanning dependencies of target pydenseflow
Scanning dependencies of target extract_gpu
Scanning dependencies of target extract_warp_gpu
Scanning dependencies of target extract_cpu
[ 66%] [ 77%] Building CXX object CMakeFiles/extract_gpu.dir/tools/extract_flow_gpu.cpp.o
[ 88%] Building CXX object CMakeFiles/extract_cpu.dir/tools/extract_flow.cpp.o
Building CXX object CMakeFiles/extract_warp_gpu.dir/tools/extract_warp_flow_gpu.cpp.o
[100%] Building CXX object CMakeFiles/pydenseflow.dir/src/py_denseflow.cpp.o
Linking CXX executable extract_gpu
Linking CXX executable extract_warp_gpu
Linking CXX executable extract_cpu
libdenseflow.a(dense_flow_gpu.cpp.o): In function `calcDenseFlowGPU(std::string, int, int, int, int, std::vector<std::vector<unsigned char, std::allocator<unsigned char> >, std::allocator<std::vector<unsigned char, std::allocator<unsigned char> > > >&, std::vector<std::vector<unsigned char, std::allocator<unsigned char> >, std::allocator<std::vector<unsigned char, std::allocator<unsigned char> > > >&, std::vector<std::vector<unsigned char, std::allocator<unsigned char> >, std::allocator<std::vector<unsigned char, std::allocator<unsigned char> > > >&, int, int)':
dense_flow_gpu.cpp:(.text+0x7d8): undefined reference to `cv::cuda::FarnebackOpticalFlow::create(int, double, bool, int, int, int, double, int)'
dense_flow_gpu.cpp:(.text+0x881): undefined reference to `cv::cuda::OpticalFlowDual_TVL1::create(double, double, double, int, int, double, int, double, double, bool)'
dense_flow_gpu.cpp:(.text+0x8ea): undefined reference to `cv::cuda::BroxOpticalFlow::create(double, double, double, int, int, int)'
dense_flow_gpu.cpp:(.text+0x12e9): undefined reference to `cv::cuda::split(cv::_InputArray const&, cv::cuda::GpuMat*, cv::cuda::Stream&)'
libdenseflow.a(dense_flow_gpu.cpp.o): In function `calcDenseFlowPureGPU(std::string, int, int, int, int, std::vector<std::vector<unsigned char, std::allocator<unsigned char> >, std::allocator<std::vector<unsigned char, std::allocator<unsigned char> > > >&, std::vector<std::vector<unsigned char, std::allocator<unsigned char> >, std::allocator<std::vector<unsigned char, std::allocator<unsigned char> > > >&, std::vector<std::vector<unsigned char, std::allocator<unsigned char> >, std::allocator<std::vector<unsigned char, std::allocator<unsigned char> > > >&)':
dense_flow_gpu.cpp:(.text+0x1b6c): undefined reference to `cv::cudacodec::createVideoReader(cv::String const&)'
dense_flow_gpu.cpp:(.text+0x1ca6): undefined reference to `cv::cuda::FarnebackOpticalFlow::create(int, double, bool, int, int, int, double, int)'
dense_flow_gpu.cpp:(.text+0x1d4f): undefined reference to `cv::cuda::OpticalFlowDual_TVL1::create(double, double, double, int, int, double, int, double, double, bool)'
dense_flow_gpu.cpp:(.text+0x1db8): undefined reference to `cv::cuda::BroxOpticalFlow::create(double, double, double, int, int, int)'
dense_flow_gpu.cpp:(.text+0x26be): undefined reference to `cv::cuda::split(cv::_InputArray const&, cv::cuda::GpuMat*, cv::cuda::Stream&)'
collect2: error: ld returned 1 exit status
make[2]: *** [extract_gpu] Error 1
make[1]: *** [CMakeFiles/extract_gpu.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
libdenseflow.a(dense_warp_flow_gpu.cpp.o): In function `calcDenseWarpFlowGPU(std::string, int, int, int, int, std::vector<std::vector<unsigned char, std::allocator<unsigned char> >, std::allocator<std::vector<unsigned char, std::allocator<unsigned char> > > >&, std::vector<std::vector<unsigned char, std::allocator<unsigned char> >, std::allocator<std::vector<unsigned char, std::allocator<unsigned char> > > >&)':
dense_warp_flow_gpu.cpp:(.text+0x23c5): undefined reference to `cv::cuda::FarnebackOpticalFlow::create(int, double, bool, int, int, int, double, int)'
dense_warp_flow_gpu.cpp:(.text+0x246e): undefined reference to `cv::cuda::OpticalFlowDual_TVL1::create(double, double, double, int, int, double, int, double, double, bool)'
dense_warp_flow_gpu.cpp:(.text+0x24d7): undefined reference to `cv::cuda::BroxOpticalFlow::create(double, double, double, int, int, int)'
dense_warp_flow_gpu.cpp:(.text+0x2da0): undefined reference to `cv::cuda::split(cv::_InputArray const&, cv::cuda::GpuMat*, cv::cuda::Stream&)'
dense_warp_flow_gpu.cpp:(.text+0x3747): undefined reference to `cv::cuda::split(cv::_InputArray const&, cv::cuda::GpuMat*, cv::cuda::Stream&)'
collect2: error: ld returned 1 exit status
make[2]: *** [extract_warp_gpu] Error 1
make[1]: *** [CMakeFiles/extract_warp_gpu.dir/all] Error 2
[100%] Built target extract_cpu

`

**Comment by victorhcm** [comment]
Just checking first, can you confirm you're on branch opencv-3.1.0?

Victor Hugo

**Comment by yangyuke001** [comment]
@victorhcm 

my envirenments : opencv 3.4.0,and I got this error:

mmaction/third_party/dense_flow/build$ cmake .. && make -j
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   python
-- Configuring done
-- Generating done
-- Build files have been written to: /home/yyk/ACTION/mmaction/third_party/dense_flow/build
Scanning dependencies of target denseflow
[  7%] Building CXX object CMakeFiles/denseflow.dir/src/dense_warp_flow_gpu.cpp.o
[ 14%] Building CXX object CMakeFiles/denseflow.dir/src/dense_flow_gpu.cpp.o
/home/yyk/ACTION/mmaction/third_party/dense_flow/src/dense_warp_flow_gpu.cpp:12:10: fatal error: opencv2/xfeatures2d.hpp: No such file or directory
 #include "opencv2/xfeatures2d.hpp"
          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
/home/yyk/ACTION/mmaction/third_party/dense_flow/src/dense_flow_gpu.cpp:5:10: fatal error: opencv2/xfeatures2d.hpp: No such file or directory
 #include "opencv2/xfeatures2d.hpp"
          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/denseflow.dir/build.make:134: recipe for target 'CMakeFiles/denseflow.dir/src/dense_warp_flow_gpu.cpp.o' failed
make[2]: *** [CMakeFiles/denseflow.dir/src/dense_warp_flow_gpu.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/denseflow.dir/build.make:110: recipe for target 'CMakeFiles/denseflow.dir/src/dense_flow_gpu.cpp.o' failed
make[2]: *** [CMakeFiles/denseflow.dir/src/dense_flow_gpu.cpp.o] Error 1
CMakeFiles/Makefile2:215: recipe for target 'CMakeFiles/denseflow.dir/all' failed
make[1]: *** [CMakeFiles/denseflow.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

any help is awseome!

**Pull request merged**
