### PR TITLE
Fix: path may contains .

### PR DESCRIPTION
**Pull request by innerlee**
Use `os.path` instead of manually parse filenames.

### CODE REVIEW

**Comment by a-whitej** [comment]
could you please give some hints about how to build dense_flow succssfully with opencv(2.4 or 3.1 version) on Ubuntu 16.04.6 LTS system? I tried days to install opencv but failed.

**Comment by innerlee** [comment]
Maybe you can try "Opencv 4.1.0". See https://github.com/open-mmlab/mmaction/blob/master/INSTALL.md

**Comment by a-whitej** [comment]
/usr/local/include/opencv2/video/tracking.hpp:442:20: note:   ‘cv::DualTVL1OpticalFlow’
dense_flow/src/dense_flow.cpp:21:13: error: ‘DualTVL1OpticalFlow’ is not a member of ‘cv::optflow’
     cv::Ptr<cv::optflow::DualTVL1OpticalFlow> alg_tvl1 = cv::optflow::DualTVL1OpticalFlow::create();

Acutally I installed opencv and opencv_contrib correctly with version 3.1 like

cmake -D CMAKE_BUILD_TYPE=RELEASE \
	-D WITH_CUDA=OFF \
	-D WITH_IPP=OFF \
	-D BUILD_opencv_python3=ON \
	-D BUILD_opencv_dnn=OFF \
	-D BUILD_opencv_hdf=OFF \
    -D CMAKE_INSTALL_PREFIX=/usr/local \
    -D INSTALL_PYTHON_EXAMPLES=ON \
    -D INSTALL_C_EXAMPLES=OFF \
    -D OPENCV_EXTRA_MODULES_PATH=~/opencv-3.1.0/opencv_contrib-3.1.0/modules \
    -D PYTHON_EXECUTABLE=~/.virtualenvs/cv/bin/python \
	-D WITH_FFMPEG=1 \
	-D HDF5_C_INCLUDE_DIR=/usr/local/hdf5/include \
    -D BUILD_EXAMPLES=OFF ..

**Comment by innerlee** [comment]
I didn't try opencv 3.1, but according to readme, the branch `opencv-3.1` https://github.com/yjxiong/dense_flow/tree/opencv-3.1 should be used.

**Pull request closed without merging**
